#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    gatewaymicroserviceapp-app:
        image: gatewaymicroserviceapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://gatewaymicroserviceapp-mysql:3306/gatewaymicroserviceapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=gatewaymicroserviceapp-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    gatewaymicroserviceapp-mysql:
        extends:
            file: mysql.yml
            service: gatewaymicroserviceapp-mysql
    # Uncomment to have Cassandra working with the gateway
    # gatewaymicroserviceapp-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: gatewaymicroserviceapp-cassandra
    # gatewaymicroserviceapp-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: gatewaymicroserviceapp-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
